repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: LICENSES/headers
  - id: check-added-large-files
  - id: check-toml
  - id: destroyed-symlinks
  - id: check-symlinks

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

- repo: https://github.com/PyCQA/autoflake
  rev: v1.7.6
  hooks:
    - id: autoflake
      args: [
        --in-place,
        --remove-all-unused-imports,
      ]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
    - id: reorder-python-imports
      name: reorder python imports inside src
      args: [
        --application-directories,
        src,
        --py37-plus,
        --add-import,
        "from __future__ import annotations",
      ]
      files: ^src
    - id: reorder-python-imports
      name: reorder python imports outside src
      exclude: ^src
      args: [
        --py37-plus,
        --add-import,
        "from __future__ import annotations",
      ]

- repo: https://github.com/myint/docformatter
  rev: v1.5.0
  hooks:
    - id: docformatter
      exclude: ^tests/.*$
      args: [
        --in-place,
        --wrap-summaries,
        "88",
        --wrap-descriptions,
        "88",
      ]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-bugbear==22.10.27
      - flake8-docstrings==1.6.0
      - flake8-print==4.0.0
      - pep8-naming==0.12.1

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
  - id: mypy
    additional_dependencies:
      - types-dataclasses
      - types-PyYAML

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
    - id: insert-license
      name: insert apache license
      files: \.py$
      args:
        - --license-filepath
        - LICENSES/headers/apache.txt
